/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        BoxMenu: typeof import("./src/components/box-menu/index.vue")["default"];
        RouterLink: typeof import("vue-router")["RouterLink"];
        RouterView: typeof import("vue-router")["RouterView"];
        Time: typeof import("./src/components/time/index.vue")["default"];
        Timer: typeof import("./src/components/timer/index.vue")["default"];
    }
}
